@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": ""
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false // root node is included
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.cleanup.todoc.ui.MainActivity"
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_856774308 { 
   	label=cleanup
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1925994771 { 
   	label=todoc
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   MainActivity592173596[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MainActivity</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   adapter: TaskListAdapter [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   allProjects: Project[] [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >+   dialog: AlertDialog [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dialogEditText: EditText [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dialogSpinner: Spinner [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   lblNoTasks: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   listTasks: RecyclerView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   taskViewModel: TaskViewModel [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- addTask(task: Task)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onChanged(tasks: List&lt;Task&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCreate(savedInstanceState: Bundle)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCreateOptionsMenu(menu: Menu): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ onDeleteTask(task: Task)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onOptionsItemSelected(item: MenuItem): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- onPositiveButtonClick(dialogInterface: DialogInterface)</TD></TR>
<TR><TD ALIGN="LEFT" >- populateDialogSpinner()</TD></TR>
<TR><TD ALIGN="LEFT" >- showAddTaskDialog()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MainActivityInstrumentedTest1258479462[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MainActivityInstrumentedTest</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   rule: ActivityTestRule&lt;MainActivity&gt; [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addAndRemoveTask()</TD></TR>
<TR><TD ALIGN="LEFT" >+ sortTasks()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Project2005803681[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Project</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   color: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: long [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getProjectById(id: long): Project</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Task2005803681[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Task</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   creationTimestamp: long [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: long [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   projectId: long [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TaskDao_Impl1258479462[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TaskDao_Impl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   __db: RoomDatabase [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   __deletionAdapterOfTask: EntityDeletionOrUpdateAdapter&lt;Task&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   __insertionAdapterOfTask: EntityInsertionAdapter&lt;Task&gt; [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ delete(task: Task)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAllTasks(order: int): LiveData&lt;List&lt;Task&gt;&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ insert(task: Task)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TaskListAdapter592173596[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TaskListAdapter</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   deleteTaskListener: DeleteTaskListener [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onBindViewHolder(taskViewHolder: TaskViewHolder, position: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCreateViewHolder(viewGroup: ViewGroup, viewType: int): TaskViewHolder</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TaskRepository1258479462[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TaskRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   mTaskDao: TaskDao [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ add(task: Task)</TD></TR>
<TR><TD ALIGN="LEFT" ># getAllTasks(order: int): LiveData&lt;List&lt;Task&gt;&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ remove(task: Task)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TaskViewHolder843697638[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TaskViewHolder</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   deleteTaskListener: DeleteTaskListener [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   imgDelete: AppCompatImageView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   imgProject: AppCompatImageView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   lblProjectName: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   lblTaskName: TextView [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># bind(task: Task)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TaskViewModel1258479462[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TaskViewModel</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   mAllTasks: LiveData&lt;List&lt;Task&gt;&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   mRepository: TaskRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sortOrder: MutableLiveData&lt;Integer&gt; [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ add(task: Task)</TD></TR>
<TR><TD ALIGN="LEFT" >+ remove(task: Task)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
MainActivity592173596 -> Project2005803681[label="allProjects
[0..*]"];
MainActivity592173596 -> TaskListAdapter592173596[label="adapter
[0..1]"];
MainActivity592173596 -> TaskViewModel1258479462[label="taskViewModel
[0..1]"];
MainActivityInstrumentedTest1258479462 -> MainActivity592173596[label="rule
[0..1]"];
TaskDao_Impl1258479462 -> Task2005803681[label="__deletionAdapterOfTask
[0..1]"];
TaskDao_Impl1258479462 -> Task2005803681[label="__insertionAdapterOfTask
[0..1]"];
TaskListAdapter592173596 -> MainActivity592173596[label="deleteTaskListener
[0..1]"];
TaskRepository1258479462 -> TaskDao_Impl1258479462[arrowhead=none, arrowtail=empty, dir=both];
TaskViewHolder843697638 -> MainActivity592173596[label="deleteTaskListener
[0..1]"];
TaskViewModel1258479462 -> Task2005803681[label="mAllTasks
[0..1]"];
TaskViewModel1258479462 -> TaskRepository1258479462[label="mRepository
[0..1]"];
    
}
@enduml